import = ["~/.config/alacritty/catppuccin-mocha.toml"]


[shell]
args = ["--login", "-c", "tmux -u attach || tmux -u new -s default"]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItaliic"

[cursor.style]
shape = "underline"
